ds = read.csv2("c:/workspaces/git/pete/raw.csv")
library(Rcmdr)
active <- subset(ds, engine == "active-bpel")
ode <- subset(ds, engine == "ode")
bpelg <- subset(ds, engine == "bpelg")
openesb <- subset(ds, engine == "openesb23")
orchestra <- subset(ds, engine == "orchestra")
petals <- subset(ds, engine == "petalsesb41")
numSummary(active$time,statistics=c("mean","sd","cv"))
numSummary(ode$time,statistics=c("mean","sd","cv"))
numSummary(bpelg$time,statistics=c("mean","sd","cv"))
numSummary(openesb$time,statistics=c("mean","sd","cv"))
numSummary(orchestra$time,statistics=c("mean","sd","cv"))
numSummary(petals$time,statistics=c("mean","sd","cv"))